version: "3.3"

services:
  db:
    container_name: receita-db
    image: postgres
    volumes:
      - ./data/db:/var/lib/postgresql/data
    ports:
        - "25432:5432"
    environment:
      - POSTGRES_DB=receitaappdb
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres

  web:
    container_name: receita-web
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - db